# Generated by Django 4.2 on 2023-04-18 10:11

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('db', '0002_user'),
    ]

    operations = [
        migrations.DeleteModel(
            name='User',
        ),
    ]
